import * as Knex from 'knex';

const TABLE_NAME = 'users';

export async function seed(knex: Knex): Promise<void> {
  // Deletes ALL existing entries
  await knex(TABLE_NAME).del();

  // Inserts seed entries
  await knex(TABLE_NAME).insert([
    {
      login: 'test',
      digest: '$2a$10$Bun85vEKplxtXDZhKm8fRemVKtjEDkvinYK.jO6smOyF5btVwohze',
      fullname: 'Vlad G',
      email: 'vovanvip@yandex.ru',
      avatar: 'https://robohash.org/nonfugavoluptatum.png?size=256x256&set=set1',
    },
    {
      login: 'encryption',
      digest: 'PEhpQB2',
      fullname: 'Dniren Joannet',
      email: 'djoannet1@uiuc.edu',
      avatar: 'https://robohash.org/consequaturmolestiassint.png?size=256x256&set=set1',
    },
    {
      login: '5th generation',
      digest: 'rv8vjqOfviD',
      fullname: 'Ronnie Waterson',
      email: 'rwaterson2@1688.com',
      avatar: 'https://robohash.org/autdoloremcumque.png?size=256x256&set=set1',
    },
    {
      login: 'definition',
      digest: 'McKoCKN',
      fullname: 'Nickie Cristoferi',
      email: 'ncristoferi3@slashdot.org',
      avatar: 'https://robohash.org/autenimdolores.png?size=256x256&set=set1',
    },
    {
      login: 'analyzing',
      digest: '5pWT0XkSmh',
      fullname: 'Yorke Hibbart',
      email: 'yhibbart4@zdnet.com',
      avatar: 'https://robohash.org/dignissimosutea.png?size=256x256&set=set1',
    },
    {
      login: 'discrete',
      digest: 'vLBHQ04nMth1',
      fullname: 'Gerhard Newing',
      email: 'gnewing5@telegraph.co.uk',
      avatar: 'https://robohash.org/illosedminima.png?size=256x256&set=set1',
    },
    {
      login: 'installation',
      digest: 'vxXKoyhaRg',
      fullname: 'Ray Onyon',
      email: 'ronyon6@vistaprint.com',
      avatar: 'https://robohash.org/temporaasperioresofficiis.png?size=256x256&set=set1',
    },
    {
      login: 'capacity',
      digest: 'zNm0li9CS3G',
      fullname: 'Abagael Dumbleton',
      email: 'adumbleton7@dagondesign.com',
      avatar: 'https://robohash.org/utdoloredeleniti.png?size=256x256&set=set1',
    },
    {
      login: 'transitional',
      digest: 'Pz3e1WnukLTK',
      fullname: 'Andreas Douris',
      email: 'adouris8@bloomberg.com',
      avatar: 'https://robohash.org/quivoluptatibusest.png?size=256x256&set=set1',
    },
    {
      login: 'optional',
      digest: 'i83kHk04X',
      fullname: 'Sashenka Fairpool',
      email: 'sfairpool9@samsung.com',
      avatar: 'https://robohash.org/temporaaccusantiumdoloribus.png?size=256x256&set=set1',
    },
    {
      login: 'content-based',
      digest: 'TiTyT0c',
      fullname: 'Ginnifer Garioch',
      email: 'ggariocha@archive.org',
      avatar: 'https://robohash.org/enimnecessitatibusperferendis.png?size=256x256&set=set1',
    },
    {
      login: 'system-worthy',
      digest: '3q4DK4i',
      fullname: 'Graeme Kerins',
      email: 'gkerinsb@guardian.co.uk',
      avatar: 'https://robohash.org/velblanditiisvel.png?size=256x256&set=set1',
    },
    {
      login: 'upgradable',
      digest: 'lIu9nQ',
      fullname: 'Hurley Derill',
      email: 'hderillc@google.com.au',
      avatar: 'https://robohash.org/cumrepudiandaeut.png?size=256x256&set=set1',
    },
    {
      login: 'optimized',
      digest: 'CA11STLZT4u',
      fullname: 'Carol Duigenan',
      email: 'cduigenand@noaa.gov',
      avatar: 'https://robohash.org/eaquearchitectopariatur.png?size=256x256&set=set1',
    },
    {
      login: 'discrete',
      digest: 'gCo6DMjU',
      fullname: 'Marty Ellwand',
      email: 'mellwande@a8.net',
      avatar: 'https://robohash.org/omnissolutaet.png?size=256x256&set=set1',
    },
    {
      login: 'monitored',
      digest: '2GfxJa',
      fullname: 'Pauline Dearnly',
      email: 'pdearnlyf@t.co',
      avatar: 'https://robohash.org/ipsaoptiosimilique.png?size=256x256&set=set1',
    },
    {
      login: '6th generation',
      digest: 'qRbpqJ0aHrK',
      fullname: 'Zara Marriot',
      email: 'zmarriotg@admin.ch',
      avatar: 'https://robohash.org/maximevoluptateporro.png?size=256x256&set=set1',
    },
    {
      login: 'implementation',
      digest: 'Pr0QL3P',
      fullname: 'Rosco Halifax',
      email: 'rhalifaxh@skyrock.com',
      avatar: 'https://robohash.org/accusantiumexvoluptatem.png?size=256x256&set=set1',
    },
    {
      login: 'empowering',
      digest: 'IDF2HM0Nh7G',
      fullname: 'Wolfie Cowlin',
      email: 'wcowlini@gravatar.com',
      avatar: 'https://robohash.org/doloremqueetprovident.png?size=256x256&set=set1',
    },
    {
      login: 'infrastructure',
      digest: 'RWCXYjJL9m',
      fullname: 'Rosanne Kinglesyd',
      email: 'rkinglesydj@php.net',
      avatar: 'https://robohash.org/fugiatsapientequibusdam.png?size=256x256&set=set1',
    },
    {
      login: 'static',
      digest: 'm5o74P',
      fullname: 'Annmaria Geraudy',
      email: 'ageraudyk@mit.edu',
      avatar: 'https://robohash.org/rationeadipisciconsequatur.png?size=256x256&set=set1',
    },
    {
      login: 'seamless',
      digest: '8fCdS9aZX6V',
      fullname: 'Lesley Farrans',
      email: 'lfarransl@cpanel.net',
      avatar: 'https://robohash.org/dolorererumlabore.png?size=256x256&set=set1',
    },
    {
      login: 'motivating',
      digest: 'qKNGV8aB',
      fullname: 'Ruthie Hazell',
      email: 'rhazellm@ifeng.com',
      avatar: 'https://robohash.org/auteadolor.png?size=256x256&set=set1',
    },
    {
      login: 'encoding',
      digest: 'm6b98LPK',
      fullname: 'Brant Cronk',
      email: 'bcronkn@typepad.com',
      avatar: 'https://robohash.org/aliquidconsecteturut.png?size=256x256&set=set1',
    },
    {
      login: 'pricing structure',
      digest: 'zJ6PmDYV7E',
      fullname: 'Chantal Limrick',
      email: 'climricko@cbsnews.com',
      avatar: 'https://robohash.org/omnisvelitut.png?size=256x256&set=set1',
    },
    {
      login: 'next generation',
      digest: 'FAKOOnERV',
      fullname: 'Caldwell Maynard',
      email: 'cmaynardp@prweb.com',
      avatar: 'https://robohash.org/illovelquia.png?size=256x256&set=set1',
    },
    {
      login: 'upward-trending',
      digest: '8BZ2DblKJvV',
      fullname: 'Caralie Grinston',
      email: 'cgrinstonq@twitpic.com',
      avatar: 'https://robohash.org/omnisquisautem.png?size=256x256&set=set1',
    },
    {
      login: 'high-level',
      digest: 'BsObCSvC',
      fullname: 'Alberto Pomphrett',
      email: 'apomphrettr@mac.com',
      avatar: 'https://robohash.org/aliasexpeditaat.png?size=256x256&set=set1',
    },
    {
      login: 'neural-net',
      digest: '7irWpl',
      fullname: 'Merrie Bewsey',
      email: 'mbewseys@google.pl',
      avatar: 'https://robohash.org/nondolorumsuscipit.png?size=256x256&set=set1',
    },
    {
      login: 'ergonomic',
      digest: '20VTLP',
      fullname: 'Lock Hogbin',
      email: 'lhogbint@nydailynews.com',
      avatar: 'https://robohash.org/exdoloremnobis.png?size=256x256&set=set1',
    },
    {
      login: 'dynamic',
      digest: 'zoMV7DQ',
      fullname: 'Kerr Newcome',
      email: 'knewcomeu@oracle.com',
      avatar: 'https://robohash.org/undeminusmodi.png?size=256x256&set=set1',
    },
    {
      login: 'open-source',
      digest: 'dR2wjrK0',
      fullname: 'Cully Adderson',
      email: 'caddersonv@unblog.fr',
      avatar: 'https://robohash.org/illumoptiomagnam.png?size=256x256&set=set1',
    },
    {
      login: 'matrix',
      digest: 'ab21oSTVhG8',
      fullname: 'Ashton Brabin',
      email: 'abrabinw@cam.ac.uk',
      avatar: 'https://robohash.org/idcommodineque.png?size=256x256&set=set1',
    },
    {
      login: 'background',
      digest: 'FywQwjXdETr',
      fullname: 'Chrissie Graine',
      email: 'cgrainex@webmd.com',
      avatar: 'https://robohash.org/etquaeid.png?size=256x256&set=set1',
    },
    {
      login: 'next generation',
      digest: 'jaEnSz1Z1me1',
      fullname: 'Mallorie Kavanagh',
      email: 'mkavanaghy@telegraph.co.uk',
      avatar: 'https://robohash.org/adipiscideseruntimpedit.png?size=256x256&set=set1',
    },
    {
      login: 'local area network',
      digest: 'xnL60XCuN',
      fullname: 'Vanya Ackrill',
      email: 'vackrillz@oakley.com',
      avatar: 'https://robohash.org/accusantiumenimsed.png?size=256x256&set=set1',
    },
    {
      login: 'streamlined',
      digest: '6vAifBB',
      fullname: 'Whitman Cleynaert',
      email: 'wcleynaert10@about.me',
      avatar: 'https://robohash.org/porroesttenetur.png?size=256x256&set=set1',
    },
    {
      login: 'multi-tasking',
      digest: '3bIzaX1zW',
      fullname: 'Chadd Manston',
      email: 'cmanston11@unicef.org',
      avatar: 'https://robohash.org/autveliste.png?size=256x256&set=set1',
    },
    {
      login: 'framework',
      digest: 'zTF95YrX',
      fullname: 'Davina Davydenko',
      email: 'ddavydenko12@princeton.edu',
      avatar: 'https://robohash.org/estverosit.png?size=256x256&set=set1',
    },
    {
      login: 'persistent',
      digest: 'DiuE4M2DrVm',
      fullname: 'Hailey Cosser',
      email: 'hcosser13@samsung.com',
      avatar: 'https://robohash.org/deleniticumquererum.png?size=256x256&set=set1',
    },
    {
      login: 'benchmark',
      digest: 'xdBuzE83EuC',
      fullname: 'Rutherford Feely',
      email: 'rfeely14@w3.org',
      avatar: 'https://robohash.org/nonnihilvoluptatem.png?size=256x256&set=set1',
    },
    {
      login: 'multi-lateral',
      digest: 'oMzo2r7p',
      fullname: 'Ade Aberkirder',
      email: 'aaberkirder15@sbwire.com',
      avatar: 'https://robohash.org/inciduntfacilisid.png?size=256x256&set=set1',
    },
    {
      login: 'internet solution',
      digest: 'g0cRSHR',
      fullname: 'Cory Baughn',
      email: 'cbaughn16@dagondesign.com',
      avatar: 'https://robohash.org/inciduntvoluptateplaceat.png?size=256x256&set=set1',
    },
    {
      login: 'model',
      digest: 'iJGfvuBd',
      fullname: 'Roxana Drury',
      email: 'rdrury17@go.com',
      avatar: 'https://robohash.org/commodiquiacumque.png?size=256x256&set=set1',
    },
    {
      login: 'motivating',
      digest: 'ccpaoaLd',
      fullname: 'Rodge Moriarty',
      email: 'rmoriarty18@diigo.com',
      avatar: 'https://robohash.org/utharumid.png?size=256x256&set=set1',
    },
    {
      login: 'artificial intelligence',
      digest: 'dzOVsVRN',
      fullname: 'Charita Danielot',
      email: 'cdanielot19@fotki.com',
      avatar: 'https://robohash.org/quissaepequi.png?size=256x256&set=set1',
    },
    {
      login: 'future-proofed',
      digest: 'SV6xXsNJf',
      fullname: 'Maximilian Gibb',
      email: 'mgibb1a@vistaprint.com',
      avatar: 'https://robohash.org/natusinventoremolestiae.png?size=256x256&set=set1',
    },
    {
      login: 'holistic',
      digest: '5Lj5zZz',
      fullname: 'Bettine Mantha',
      email: 'bmantha1b@acquirethisname.com',
      avatar: 'https://robohash.org/harumautet.png?size=256x256&set=set1',
    },
    {
      login: 'tangible',
      digest: 'pW0A4X',
      fullname: 'Marty Caccavale',
      email: 'mcaccavale1c@msn.com',
      avatar: 'https://robohash.org/laboreoditsint.png?size=256x256&set=set1',
    },
    {
      login: 'product',
      digest: 'n27UOxPiXnh',
      fullname: 'Roselle Hudson',
      email: 'rhudson1d@123-reg.co.uk',
      avatar: 'https://robohash.org/quodmagnamqui.png?size=256x256&set=set1',
    },
  ]);
}
